/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/markthal.glb");
  return (
    <group is="group" ref={group} {...props} dispose={null}>
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_3_Mat_none_Tex_261.geometry}
        material={nodes.Mesh_3_Mat_none_Tex_261.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_2_Mat_none_Tex_259.geometry}
        material={nodes.Mesh_2_Mat_none_Tex_259.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_0_Mat_none_Tex_258.geometry}
        material={nodes.Mesh_0_Mat_none_Tex_258.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_1_Mat_none_Tex_257.geometry}
        material={nodes.Mesh_1_Mat_none_Tex_257.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_3_Mat_none_Tex_261001.geometry}
        material={nodes.Mesh_3_Mat_none_Tex_261001.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_2_Mat_none_Tex_259001.geometry}
        material={nodes.Mesh_2_Mat_none_Tex_259001.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_0_Mat_none_Tex_258001.geometry}
        material={nodes.Mesh_0_Mat_none_Tex_258001.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_1_Mat_none_Tex_257001.geometry}
        material={nodes.Mesh_1_Mat_none_Tex_257001.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_3_Mat_none_Tex_261002.geometry}
        material={nodes.Mesh_3_Mat_none_Tex_261002.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_2_Mat_none_Tex_259002.geometry}
        material={nodes.Mesh_2_Mat_none_Tex_259002.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_0_Mat_none_Tex_258002.geometry}
        material={nodes.Mesh_0_Mat_none_Tex_258002.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_1_Mat_none_Tex_257002.geometry}
        material={nodes.Mesh_1_Mat_none_Tex_257002.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.o8.geometry}
        material={nodes.o8.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.o9.geometry}
        material={nodes.o9.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_4_Mat_none_Tex_260.geometry}
        material={materials.Material_whitesteel_co}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_1_Mat_none_Tex_256.geometry}
        material={materials.Material_market_hall_brick}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_3_Mat_none_Tex_257.geometry}
        material={nodes.Mesh_3_Mat_none_Tex_257.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_0_Mat_none_Tex_0.geometry}
        material={nodes.Mesh_0_Mat_none_Tex_0.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Mesh_2_Mat_none_Tex_512.geometry}
        material={materials.Material_markethall_rot}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Shops.geometry}
        material={nodes.Shops.material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
      />
      <mesh is="mesh"
        castshadow
        receiveshadow
        geometry={nodes.g1004.geometry}
        material={materials["Default_Mat.007"]}
      />
    </group>
  );
}

useGLTF.preload("/markthal.glb");
